application:
  version: "@project.version@"

spring:
  application:
    name: golde-raspberry-api
  mvc:
    static-path-pattern: "/**"
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MSSQLServer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    sql:
      init:
        mode: always

server:
  servlet:
    context-path: /golden-raspberry-api

logging:
  level:
    org:
      springframework:
        security: DEBUG

flyway:
  enabled: true
  locations: db/migration
  baseline-on-migrate: true

csv-movie:
  directory: src/main/resources/simulation/Movielist.csv
