create table movie (
   movie_id  bigint generated by default as identity,
   producers varchar(255) not null,
   studios   varchar(255) not null,
   title     varchar(255) not null,
   winner    bit          not null,
   "year"    integer      not null,
   primary key (movie_id)
)